### PR TITLE
MONIT-41181: address CVE in @adobe/css-tools

### PR DESCRIPTION
**Pull request by bcutler-work**
https://github.com/adobe/css-tools/security/advisories/GHSA-hpx4-r86g-5jrg

### CODE REVIEW

**Comment by ssama-vmware** [comment]
Missing the change in package.json?

**Review by ssama-vmware — COMMENTED** [review]
Missing the change in package.json?

**Comment by bcutler-work** [comment]
It's not a direct dependency, it's a dependency of `@testing-library/jest-dom`.

**Comment by ssama-vmware** [comment]
> It's not a direct dependency, it's a dependency of `@testing-library/jest-dom`.

Please update `@testing-library/jest-dom` in order to resolve CVE. Direct change in lock file is not recommended

**Comment by bcutler-work** [comment]
Ended up removing the RTL dependency entirely since there aren't any actual tests in that directory, I think it was leftover boilerplate.

**Review by ssama-vmware — APPROVED** [review]

**Pull request merged**
